### PR TITLE
Non ortho fix

### PR DESCRIPTION
**Pull request by jaxmatrix**
I am working on the issue #439 

I have added the matrix required for mapping texture to the non-orthogonal box. For this I have re-calculated the dimension of the box that is going to render the volumetric information and added an additional Matrix4 `textmap` which takes the vectors that are used to define the non-orthogonal box dimension in the volume.js. 

This currently works fine with the .cube format remaining formats are to be tested. I am currently working on to make this work for .dx file formats.

Test file can be found in tests/non-ortho-box.html and that are rendered are added in test/test_structs.

image

image

I have checked the volumetric rendering using ChimeraX visualizer

Following are the images generated from [ChimeraX](https://www.rbvi.ucsf.edu/chimerax/)

image

image

image

### CODE REVIEW

**Comment by dkoes** [comment]
Thank you for this contribution.

The box still looks orthonormal? The edges aren't at an angle.
box

In the future, please do not commit whitespace changes with code changes. It makes it much harder to review the code.
The test needs to be put into the test framework

**Comment by jaxmatrix** [comment]
I will keep that in mind to take care of the whitespaces. Actually I did few experiments with the mapping of texture, in which I found that we actually don't need a non-orthogonal box. 

We can have our textmap such that it access the volumetric coordinates in the following fashion
image

Here we can see the oblique cube embedded inside the orthogonal points. 

So when we sample the points inside the orthogonal cube, their coordinate are converted to coordinate of system of vector specified in the volumetric data file. Now so if the point that we are sampling belongs to point volumetric data then it will have coordinates between 0 to 1 and for remaining coordinate it will lie outside this range.

Now the outer box that I have defined has the dimension encapsulating the farthest coordinate of the volumetric data. I am still not complete sure about this though. This could have been a lucky case where this logic worked. I am still working on it to clear my hypothesis.

I will shortly share my observations that made me conclude this.

**Comment by dkoes** [comment]
Yes, you do a coordinate conversion, but when the converted point lands outside the box, no density should be generated so you should end up with a slanted looking box of density.

**Comment by jaxmatrix** [comment]
I think the volume intersecting with the box. I will fix it this week end.

**Comment by dkoes** [comment]
There may have been an issue with the incorporation of the translation matrix.  I've made several improvements to the cube handling code and added your example (with isosurfaces) as a test:
http://3dmol.org/tests/auto/generate_test.cgi?test=testcubemol

The goal should be to have the same test with volumetric rendering. A transfer function ranging from 0.03 to 0.075 should look good.

**Comment by jaxmatrix** [comment]
Okay, Thanks. It will be really helpful. I am also thinking of adding a volumetric cube data for the tests so that we can see how are the vectors transforming with our texture map function. 

Earlier I used the "coordinate value as the color in shader.js" to look up how the vectors are being transformed inside the box.

**Comment by jaxmatrix** [comment]
PS: I wrote a script to create non orthogonal boxes (.cube format) and I am testing the volumetric rendering, secondly for this example I replaced the color with coordinates of the mapped coordinates.

I corrected the problem with points outside the box, but another issue came up, as per the calculation the dimension of the box and the inverse matrix should be same but when I render it the volumetric region is partially clipped. 

Volumetric box
image
image


Volumetric box with manual scaling of textmap matrix (matrix to non-orthogonal coordinates to orthogonal coordinates) 
image
image
image


Original box : 
image

So can you share some reference to the following two lines:
```
texmatrix.makeTranslation(-data.origin.x/xoff,-data.origin.y/yoff,-data.origin.z/zoff);
texmatrix.scale({x:1.0/xoff, y:1.0/yoff, z:1.0/zoff});
```

**Comment by dkoes** [comment]
How is this coming?  Should I wait for it to be finished before making the next point release?

**Comment by jaxmatrix** [comment]
No, I am still working on it, I am new to graphics programming so I might need some time to fix it. I added one more condition in the shader similar to that for `seengood`. There is some scaling issue in the texture mapping matrix that I have introduced in the code.

**Pull request closed without merging**
