### PR TITLE
[Bug] - Fixes Caching and CodeQL Workflows

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**

- PR Adds Caching of Workflows
- PR Fixes CodeQL Workflows

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@dkoes This PR is Ready for Review as well :)

**Comment by dkoes** [comment]
Still doesn't work.  You need to test the CI with and without the cache (the first time it runs it will work because there is nothing in the cache). At best it saves 40 seconds.

**Comment by adithyaakrishna** [comment]
This is a bit strange, https://github.com/adithyaakrishna/3Dmol.js/actions/runs/5252761546/jobs/9489220710 - Test passes on the fork but not on PR :/

**Comment by adithyaakrishna** [comment]
Closing this and will open a new PR for the same :)

**Pull request closed without merging**
