### PR TITLE
Update VASP parsing for `addUnitCell` to work for POSCAR, CONTCAR files

### PR DESCRIPTION
**Pull request by mkhorton**
Referencing #295 

My JavaScript is a bit rusty, but I think this should work? Would be happy to contribute further patches once my understanding of 3Dmol.js is improved.

### CODE REVIEW

**Comment by dkoes** [comment]
Looks reasonable to me.. any chance of getting a test case added to tests/auto/tests?

**Comment by mkhorton** [comment]
Sure, will look into it.

**Comment by mkhorton** [comment]
Sorry, I'm a little confused as to how the auto tests work. What's the purpose of the cgi script, can these tests only run when deployed on a server and not locally?

I tried opening tests/index.html, but clicking the static image just links to tests/auto/generate_test.cgi?test=test1.

I think a good place to test this would be in test46, I've added a change here:

https://github.com/mkhorton/3Dmol.js/commit/7f30db85e30e594af5bf3ade9a831d4f315ac165

However I'm not sure how to actually deploy this to see if it works? Many thanks.

**Comment by dkoes** [comment]
Yes, to view the tests individually you need to be using a webserver, but you still should be able to load them all: http://3dmol.csb.pitt.edu/tests/auto/tests.html

**Pull request merged**
