### PR TITLE
Added 'per-atom opacity' functionality

### PR DESCRIPTION
**Pull request by bassemhermina**
solving issue #166 
there was a problem with the blank render path, I can't find a proper way without hacking through the legibility of the code to get it to render with opacity = 0 (when the varying opacity is enabled the opacity is not a single value but it's a buffer, and the shader is already built this time so I don't get to have the option of using the single value uniform opacity in the shader) so the only solution that I had in mind was to create another buffer with blank opacities (0,0,0,0,..) through the whole array but that would be a waste.
the other solution/trick that I used is that in the shader I multiply then divide the varying opacity value with the uniform one (ex: opacity_value = varying_opacity * uniform_opacity / uniform_opacity) , that has 2 outcomes:
1- when uniform_opacity is a non zero value, it's canceled and becomes * 1
2- when it's zero (blank render path) , it cancels the varying_opacity and the outcome is 0

### CODE REVIEW

**Comment by bassemhermina** [comment]
I created the test file, which has let me see some error in the visual output, the objects which have multiple opacities are rendered in the "transparent" render path which makes them not visible vehind other transparent objects.
So a work arround would be to have multiple opacity buffers, each for each render path, and that would solve the blank render problem too.

**Comment by dkoes** [comment]
Overlapping transparency is a separate issue.

**Comment by dkoes** [comment]
Can you explain what you mean by "blank rendering path".  I still don't get it.

**Comment by bassemhermina** [comment]
Ohh, I'm finishing the final details of the multiple opacity buffers work arround. Will push it in an hour or so.

**Comment by bassemhermina** [comment]
Yes, the  'renderObjects' function have 3 variants , regarding the materialType parameter. 
And when it gets the materialType as 'blank' , it sets the opacity value to 0
But the single valued opacity is not used when the object have multiple opacities/styles and the used value is the opacity buffer

**Comment by bassemhermina** [comment]
Aparently the technique I've followed have failed, because opaque objects have to be rendered before the transparent ones, but having an object which is both opaque and transparent causeed it to be wrongly rendered, so apparantly I'll have to divide the object into smaller entities like what has been done to 'cartoon' objects!

**Comment by bassemhermina** [comment]
> Could you add one more test that uses a small molecule rendered with spheres where a few individual atoms are made transparent (e.g., take caffeine and make only nitrogens transparent). That will make the feature more obvious.
- Sure!

> But you don't see the opaque atoms through the transparent ones.
- that’s what I meant by my comment when I mentioned that the a multiopacity molecule should be divided into smaller ones with a contant opacity, to be rendered individually, may be that can be put into another issue.

**Comment by dkoes** [comment]
What I would do is preprocess the geometries so they are labeled as fully opaque, fully transparent, or mixed.  For the mixed geometries, the shader is run twice - the first time non-opaque triangles are ignored and the second opaque triangles are ignored.

More efficient would be to segment the geometries into opaque and transparent parts, but that is more involved.

**Comment by bassemhermina** [comment]
Yes exactly, I thought about that second solution, as the first would face some problems because of the arrangement of render calls with other molecule objects; but there isn't enough time to finish it before GSoC deadline besides I have midterm exams ongoing right now, so what do you think?

**Comment by dkoes** [comment]
Yes, prioritize the proposal.

**Comment by bassemhermina** [comment]
Ok, great! I'll get back to the issue in a week or 10 days, see you in GSoC :V haha

**Comment by dkoes** [comment]
Why closed?

**Comment by bassemhermina** [comment]
The approach was totally wrong so I reset the fork and deleted all the edits in my commits to start fresh.

**Pull request closed without merging**
